version: "3.9"
services:
  dev:
    image: ghcr.io/newspaper8459/misaizu-image:latest
    shm_size: "32g"
    volumes:
      - .:/sandbox
      - ./uv-cache:/root/.cache/uv
    working_dir: /sandbox
    stdin_open: true
    tty: true
      #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  uv-cache:

