"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 500
command_timeout = 500

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[container]
format = '\[[$symbol \[$name\]]($style)\]'

[cpp]
format = '\[[$symbol($version(-$name))]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[\($hash$tag\)]($style)\]'

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
format = '\[[  (${version})(\($virtualenv\))]($style)\]'

[status]
format = '\[[$symbol$status]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[username]
format = '\[[$user]($style)\]'
